/*
 * Real ansonpdr.com product data, keyed by anson product handle (= glue id).
 *
 * Generated by tools/build-anson-data.mjs, re-run to refresh.
 *
 * Rich entries (image + description) come from the original products.json
 * scrape; entries newly added by the live catalog crawl link by URL only
 * until the next re-scrape. The UI degrades gracefully, GlueCard hides the
 * "Product details" toggle when description is missing and falls back to a
 * tinted placeholder when imageUrl is null.
 */

export interface AnsonProduct {
  matched: true;
  /** Real product title from ansonpdr.com. */
  name: string;
  /** Primary product image URL (no version query string). null when we know
   *  the product exists on Anson but haven't captured its image yet. */
  imageUrl: string | null;
  /** Optional plain-text product description. The card hides the details
   *  toggle when missing. */
  description?: string;
  /** Canonical product page on ansonpdr.com. */
  productUrl: string;
}

export interface UnmatchedProduct {
  matched: false;
}

export type GlueProduct = AnsonProduct | UnmatchedProduct;

export const ansonProducts: Record<string, GlueProduct> = {
  "anson-pdr-black-glue": {
    matched: true,
    name: "Anson Black Hot Melt PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-black-hot-pdr-glue-silver-foil-pouch-a1b2c3.jpg",
    description: "Anson Black Hot Melt PDR Glue is a premium quality adhesive designed for Paintless Dent Repair (PDR) professionals. This specialized black glue offers superior adhesion and a strong bond, ensuring efficient and effective dent removal without damaging the vehicle's paint. Its hot melt formula provides a quick set time, allowing for faster workflow and increased productivity. Proudly made in the USA, Anson PDR Glue is formulated for durability and reliability, making it an essential tool for achieving flawless repairs on all types of vehicles. Trust Anson for your PDR needs.",
    productUrl: "https://ansonpdr.com/products/anson-pdr-black-glue",
  },
  "dentout-yellow-pdr-glue": {
    matched: true,
    name: "DentOut Yellow Hot Melt PDR Glue - Cold Weather",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Dent-Out-yellow-hot-pdr-glue-sticks-cold-weather-f8a3b1c2.jpg",
    description: "Ensure effective paintless dent repair, even in colder temperatures, with Dent Out Yellow Hot Melt PDR Glue. This specially formulated glue provides a strong, reliable bond for PDR tools, allowing for precise pulling and lifting of dents without damaging the vehicle's finish. Its vibrant yellow color ensures visibility during application. Designed for seamless repairs in various weather conditions, shines in cold weather.",
    productUrl: "https://ansonpdr.com/products/dentout-yellow-pdr-glue",
  },
  "dent-slayer-cold-climate-collision-glue": {
    matched: true,
    name: "Dent Slayer Cool Climate",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/Photoroom_002_20250529_135741.jpg",
    productUrl: "https://ansonpdr.com/products/dent-slayer-cold-climate-collision-glue",
  },
  "elimadent-brazilian-blue": {
    matched: true,
    name: "Brazilian Blue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/Photoroom_20241212_151055.png",
    productUrl: "https://ansonpdr.com/products/elimadent-brazilian-blue",
  },
  "swiss-blue-pdr-glue-plain-jane": {
    matched: true,
    name: "Swiss Blue Hot Melt PDR Glue - Plain Jane",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Plain-Janes-wiss-blue-pdr-glue-a1b2c3d4.jpg",
    description: "Introducing the Swiss Blue Hot PDR Glue from Plain Jane, your go-to solution for professional Paintless Dent Repair. This high-performance glue is formulated for optimal adhesion and easy removal, ensuring a clean finish every time. Its vibrant Swiss Blue color makes it easy to track during application. Designed for use with PDR slide hammers and glue systems, this glue provides the strong bond needed to pull dents effectively without damaging the surrounding paint. Mainly a cold weather glue that deliver exceptional results, making your repair process smoother and more efficient.",
    productUrl: "https://ansonpdr.com/products/swiss-blue-pdr-glue-plain-jane",
  },
  "tequila-pdr-tools-ice-glue": {
    matched: true,
    name: "Tequila Ice Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/products/teq-cold.png",
    description: "Tequila Ice Glue - Cold Weather Hot glue",
    productUrl: "https://ansonpdr.com/products/tequila-pdr-tools-ice-glue",
  },
  "black-burro-pdr-glue": {
    matched: true,
    name: "Burro Black Widow Hot Melt PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Burro-black-widow-pdr-glue-a1b2c3d4.jpg",
    description: "Introducing the Burro Black Widow Hot Melt PDR Glue, engineered for superior performance in Paintless Dent Repair. This premium PDR glue offers exceptional adhesion and a strong bond, ensuring efficient and effective dent removal. Its specialized formula is designed to work seamlessly with PDR tools, providing the reliability professionals demand. Proudly made in the all weather good.",
    productUrl: "https://ansonpdr.com/products/black-burro-pdr-glue",
  },
  "glexo-pdr-hail-yellow": {
    matched: true,
    name: "Glexo PDR/Hail Yellow",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-glexo-pdr-hail-yellow-glue-sticks-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/glexo-pdr-hail-yellow",
  },
  "root-beer-pdr-glue": {
    matched: true,
    name: "Root Beer Hot PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-root-beer-hot-pdr-glue-sticks-a1b2c3d4.jpg",
    description: "This Super Premium PDR Dent Removal Adhesive is destined to be the choice of professional Dent Repair techs in \"Hot Weather\" and \"Big Dent\" removal. Anson PDR, is proud to be the industry leader in PDR Glue Adhesives. For technicians that purge glues, Root Beer glue purges well with Xtreme Purple in warm weather and Anson White in cooler temperatures. Enjoy the NEW Root Beer Super Premium formula!",
    productUrl: "https://ansonpdr.com/products/root-beer-pdr-glue",
  },
  "brazilian-green-hot-glue-10-sticks": {
    matched: true,
    name: "Brazilian Green",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-brazilian-green-hot-glue-sticks-10pk-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/brazilian-green-hot-glue-10-sticks",
  },
  "burro-pink-pdr-glue": {
    matched: true,
    name: "Pink Hot PDR Glue  - Burro Bubble Gum",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-pink-pdr-Bubble-Gum-glue-sticks-a1b2c3d4.jpg",
    description: "Burro Bubble Gum Pink PDR Glue - This PDR glue has quickly risen to become a favorite among dent removal technicians. This dent removal glue performs best during warm to hot weather but can be used during the cooler months. Don't let the pink color fool you these dent removal glue sticks pack a punch. The Pink PDR glue sticks from Burro give a strong pull and drips and runs out of your glue gun less than normal PDR glues. The Burro Bubble Gum Pink glue come in re-usable heavy duty bags with 10 pieces of 10-inch glue sticks.",
    productUrl: "https://ansonpdr.com/products/burro-pink-pdr-glue",
  },
  "carbon-tech-slime-pdr-glue-by-anson-pdr": {
    matched: true,
    name: "Carbon Tech Slime PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/products/img_2148.jpg",
    description: "High humidity, warm temp adhesive designed specifically for hail techs.",
    productUrl: "https://ansonpdr.com/products/carbon-tech-slime-pdr-glue-by-anson-pdr",
  },
  "pink-snapper-pdr-glue-by-dead-on-dent-tools": {
    matched: true,
    name: "Dead Dent Tools Pink Snapper PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/products/image_9a45b1b1-835d-4cbb-bdc3-1d9f664bd49a.png",
    description: "High humidity, warm temp adhesive designed specifically for hail techs.",
    productUrl: "https://ansonpdr.com/products/pink-snapper-pdr-glue-by-dead-on-dent-tools",
  },
  "dent-gents-chocolate-thunder-hot-glue": {
    matched: true,
    name: "Chocolate Thunder",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Dent-Gents-chocolate-thunder-glue-sticks-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/dent-gents-chocolate-thunder-hot-glue",
  },
  "dentout-red-pdr-glue": {
    matched: true,
    name: "DentOut Red Hot Melt PDR Glue - High Temp & Humidity",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-dentout-red-hot-pdr-glue-sticks-a1b2c3d4.jpg",
    description: "Introducing DentOut Red Hot Melt PDR Glue Sticks, engineered for superior performance in challenging conditions. These high-temperature glue sticks are specifically formulated to maintain their integrity and adhesion in both high heat and high humidity environments, ensuring reliable paintless dent repair (PDR) results. Their vibrant red color makes them easy to spot and manage during your repair process. DentOut deliver consistent, effective dent removal, even when the weather is working against you. Ideal for auto body professionals and DIY enthusiasts seeking dependable PDR solutions.",
    productUrl: "https://ansonpdr.com/products/dentout-red-pdr-glue",
  },
  "purple-perfection-pdr-glue-by-dent-reaper": {
    matched: true,
    name: "Purpull Perfection PDR Hot Melt Glue by Dent Reaper",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Dent-Reaper-purpull-perfection-pdr-glue-sticks-a1b2c3d4.jpg",
    description: "PurPull Perfection was formulated to be the best all around all weather PDR glue available, as a hybrid PDR Tech I wanted a glue that would perform in as many scenarios as possible. I think we did just that! Premium hot glue temperature rated around 60° to 90° Fahrenheit. Excellent Hail rail glue. Will exceed your expectations on large collision damage as well. Translucent Purple in color.",
    productUrl: "https://ansonpdr.com/products/purple-perfection-pdr-glue-by-dent-reaper",
  },
  "pdr-glue-traxx": {
    matched: true,
    name: "Glue Traxx -  Hot MeltPDR glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-glue-traxx-hot-pdr-glue-sticks-teal-a1b2c3d4.jpg",
    description: "Introducing Glue Traxx Hot Melt PDR Glue Sticks, your go-to solution for professional Paintless Dent Repair. Engineered for optimal adhesion and controlled set times, these glue sticks ensure a strong bond without damaging your vehicle's finish. The unique formula provides excellent pulling power, making dent removal efficient and effective. Proudly made in the USA, Glue Traxx offers the reliability and performance that auto body professionals demand. Get the job done right with our premium PDR glue sticks.",
    productUrl: "https://ansonpdr.com/products/pdr-glue-traxx",
  },
  "orange-fire-pdr-glue-systems": {
    matched: true,
    name: "Orange Fire - Hot Melt Glue - PDR Glue Systems",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-orange-fire-glue-sticks-dent-repair-a1b2c3.jpg",
    description: "Introducing Orange Fire PDR Glue Sticks, One of our best selling hot weather glue, engineered for superior performance in paintless dent repair. These vibrant orange glue sticks offer exceptional adhesion and a fast set time, ensuring efficient and effective dent removal. Made in the USA, Orange Fire glue sticks are designed to work seamlessly with PDR glue systems, providing a reliable bond that won't damage your vehicle's finish. Experience the power and precision of Orange Fire for professional-grade results on every repair.",
    productUrl: "https://ansonpdr.com/products/orange-fire-pdr-glue-systems",
  },
  "tequila-pdr-glue": {
    matched: true,
    name: "Tequila Turquoise PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/products/tequila_bag_v3ar-1.jpg",
    description: "Tequila Turquoise hot glue is ideal for every day mid temperature weather, low humidity.",
    productUrl: "https://ansonpdr.com/products/tequila-pdr-glue",
  },
  "willey-quick-brazilian-hot-glue": {
    matched: true,
    name: "Hangin' Honey (Gold Rush)",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-hangin-honey-hot-glue-sticks-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/willey-quick-brazilian-hot-glue",
  },
  "brazilian-tropical-hail-hot-glue": {
    matched: true,
    name: "Brazilian Tropical Hail",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Brazillian-tropical-hot-glue-sticks-red-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/brazilian-tropical-hail-hot-glue",
  },
  "hawg-hot-pdr-glue-just-black": {
    matched: true,
    name: "Hawg \"Just Black\"",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-hawg-hot-pdr-glue-black-f3a1b7.jpg",
    productUrl: "https://ansonpdr.com/products/hawg-hot-pdr-glue-just-black",
  },
  "yellow-jacket-pdr-glue-systems": {
    matched: true,
    name: "Yellow Jacket Hot Melt PDR Glue - PDR Glue Systems",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-yellow-jacket-pdr-glue-warm-weather-f1a2b3c4.jpg",
    description: "Unleash the power of Yellow Jacket Hot PDR Glue for superior paintless dent repair. This high-performance glue is designed for professionals seeking reliable and effective dent removal solutions. Its unique formula ensures a strong bond for pulling dents, while its hot application provides optimal working time. Experience efficient and clean dent repair with Yellow Jacket, a trusted name in PDR glue systems. Get the results you need with this essential tool for any PDR technician.",
    productUrl: "https://ansonpdr.com/products/yellow-jacket-pdr-glue-systems",
  },
  "tequila-pdr-fire-glue": {
    matched: true,
    name: "Tequila Fire Hot Melt Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-tequila-fire-glue-hot-weather-skull-design-a1b2c3d4.jpg",
    description: "Designed for durability and a strong bond, these glue sticks are perfect for warmer temperature. Whether you're working with hail or large damage Tequila Fire provides a reliable hold. Proudly made in the USA, these high-quality glue sticks ensure your tabs stay bonded.",
    productUrl: "https://ansonpdr.com/products/tequila-pdr-fire-glue",
  },
  "red-chile-pdr-glue-systems": {
    matched: true,
    name: "Red Chile PDR Hot Melt Glue Sticks - PDR Glue Systems",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-red-chile-pdr-hot-glue-sticks-a1b2c3d4.jpg",
    description: "PDR Glue Systems Red Chile dent removal glue is a high strength hot weather glue that is an imported European formula. These dent repair glue sticks have been used overseas by dent removal technicians for years and only recently PDR Glue Systems has imported this great dent glue and made it available to technicians in the USA. The Red Chile PDR glue sticks have a quick set time in the heat of the summer and give a strong pull.",
    productUrl: "https://ansonpdr.com/products/red-chile-pdr-glue-systems",
  },
  "white-pdr-glue-sticks-anson": {
    matched: true,
    name: "White hot PDR Glue - Anson PDR",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-white-hot-pdr-glue-sticks-a1b2c3d4.jpg",
    description: "White Anson PDR Glue - We are now carrying ansonpdr.com brand high-strength PDR glue. These glue sticks are white and give a high-strength, strong glue pull. We had several professional PDR companies test the ansonpdr.com white glue sticks. Each of the technicians have stated that this glue gives one of the strongest pulls when compared to other glues on the market. This is an all-weather glue; however, we have seen this glue perform at its best during moderate to cool temps.",
    productUrl: "https://ansonpdr.com/products/white-pdr-glue-sticks-anson",
  },
  "green-pdr-glue-sticks-burro": {
    matched: true,
    name: "Burro Cactus Green - Hot Melt PDR glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/ansonpdr-cactus-green-pdr-glue-sticks-a1b2c3d4_5011737b-056d-40db-8335-9a9920897700.jpg",
    description: "Burro Cactus Green - these PDR glue sticks have been the tried and true all-weather dent removal glue sticks trusted by paintless dent repair technicians for years. If you are in need of a just one kind of PDR glue stick that will work in almost all climates this is the one for you. The Burro Cactus Green dent removal glue sticks are the classic original green PDR glue that has been trusted by the professional PDR industry for many years.",
    productUrl: "https://ansonpdr.com/products/green-pdr-glue-sticks-burro",
  },
  "elimadent-brazilian-green": {
    matched: true,
    name: "Brazilian Green",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/Photoroom_001_20250529_135741.jpg",
    productUrl: "https://ansonpdr.com/products/elimadent-brazilian-green",
  },
  "glexo-hot-melt-glue-30-sticks": {
    matched: true,
    name: "Glexo Hot Melt (30 sticks)",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Glexo-Collision-Glue-Hot-climate-Collision-Glue-Hot-climatehot-melt-glue-sticks-30pcs-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/glexo-hot-melt-glue-30-sticks",
  },
  "hawg-pdr-glue-daniel-gromm": {
    matched: true,
    name: "Hawg Hot Melt PDR Glue - Just Orange",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-hawg-hot-pdr-glue-orange-sticks-a1b2c3d4.jpg",
    description: "Introducing Hawg Hot Melt PDR Glue - Just Orange, the ultimate solution for all-around temperature paintless dent repair. Developed by DG, this specially formulated orange glue provides a strong, reliable bond for thicker metal, tanks, and roof rails. Its unique composition ensures optimal performance in various conditions, making it a go-to choice for PDR professionals. Proudly made in the USA, Hawg Glue delivers exceptional strength and durability, helping you achieve flawless repairs every time. Trust Hawg Glue for your most demanding PDR jobs.",
    productUrl: "https://ansonpdr.com/products/hawg-pdr-glue-daniel-gromm",
  },
  "xtreme-purple-pdr-glue-plain-jane": {
    matched: true,
    name: "Xtreme Purple Hot PDR Glue - Plain Jane PDR",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Plain-Jane-xtreme-purple-pdr-glue-sticks-a1b2c3d4.jpg",
    description: "Plain Jane Xtreme Purple - The Plain Jane Xtreme Purple glue is a high strength all weather dent removal glue. The purple PDR glue is working best in warm to cool weather and is best when used with a high-temperature glue gun. This dent repair glue gives you a great strong glue pull and is removed easily with 91% isopropyl alcohol.",
    productUrl: "https://ansonpdr.com/products/xtreme-purple-pdr-glue-plain-jane",
  },
  "tab-weld-pdr-glue": {
    matched: true,
    name: "Tab Weld Hot Melt PDR Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/ansonpdr-tabweld-pdr-glue-sticks-a1b2c3.jpg",
    description: "Tab Weld Hot Melt PDR Glue sticks are expertly formulated for superior adhesion and performance in Paintless Dent Repair (PDR). These high-quality glue sticks ensure a strong, reliable bond to effectively pull dents without damaging your vehicle's paint. Designed for professional use, they offer consistent results and easy application with any standard PDR glue gun. Proudly made in the USA, Tab Weld PDR glue sticks are the trusted choice for auto body technicians seeking efficiency and precision in their repair work. Achieve flawless finishes and restore your vehicle's appearance with confidence.",
    productUrl: "https://ansonpdr.com/products/tab-weld-pdr-glue",
  },
  "willey-quick-tuggin-teal-hot-glue": {
    matched: true,
    name: "Tuggin' Teal",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-Willey-Quick-tuggin-teal-hot-glue-sticks-a1b2c3d4_8c82abfc-e32d-4beb-887f-1f0843ea57df.jpg",
    productUrl: "https://ansonpdr.com/products/willey-quick-tuggin-teal-hot-glue",
  },
  "collision-glue-hard-pull-hot": {
    matched: true,
    name: "Collision Hard Pull Hot Melt Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-collision-hard-pull-glue-dent-repair-a1b2c3d4.jpg",
    description: "The Anson Collision Hard Pull Glue Hot is designed for professional auto body repair. This specialized glue is formulated to provide a strong, reliable bond for dent pulling applications, ensuring efficient and effective repairs. Its high-tack formula grips firmly, allowing for precise manipulation and removal of dents. Ideal for collision repair technicians seeking dependable tools for restoring vehicle surfaces to their original condition. Trust Anson Collision for quality repair solutions.",
    productUrl: "https://ansonpdr.com/products/collision-glue-hard-pull-hot",
  },
  "camauto-bare-metal-glue": {
    matched: true,
    name: "CAMAUTO Bare Metal Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/PhotoRoom_001_20230713_134005.jpg",
    productUrl: "https://ansonpdr.com/products/camauto-bare-metal-glue",
  },
  "camauto-glue-pack-of-10": {
    matched: true,
    name: "CAMAUTO Glue (Pack of 10)",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/image_2693da53-3853-4947-bb68-5d66b0466ff9.jpg",
    productUrl: "https://ansonpdr.com/products/camauto-glue-pack-of-10",
  },
  "dent-slayer-collision-glue-hot": {
    matched: true,
    name: "Dent Slayer Hot Climate Collision",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-dent-slayer-collision-glue-hot-climate-repair-a1b2c3d4.jpg",
    productUrl: "https://ansonpdr.com/products/dent-slayer-collision-glue-hot",
  },
  "glexo-gpr-collision-red": {
    matched: true,
    name: "Glexo GPR/Collision Red",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/glexo-redhot-Photoroom_1.jpg",
    productUrl: "https://ansonpdr.com/products/glexo-gpr-collision-red",
  },
  "pdr-outlet-glue": {
    matched: true,
    name: "PDR Outlet Glue",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/Photoroom_000_20240523_133200.jpg",
    productUrl: "https://ansonpdr.com/products/pdr-outlet-glue",
  },
  "perfect-pull-collision-glue-pack-of-10": {
    matched: true,
    name: "Perfect Pull Collision (Box of 40)",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/PerfectPullGlue2.png",
    productUrl: "https://ansonpdr.com/products/perfect-pull-collision-glue-pack-of-10",
  },
  "tequila-pdr-collision-glue": {
    matched: true,
    name: "Tequila Collision (Nude)",
    imageUrl: "https://cdn.shopify.com/s/files/1/0499/2545/6040/files/anson-pdr-tequila-collision-glue-sticks-f3a7b1c9.jpg",
    productUrl: "https://ansonpdr.com/products/tequila-pdr-collision-glue",
  },
};

export function getAnsonProduct(glueId: string): GlueProduct | undefined {
  return ansonProducts[glueId];
}
